name: Deploy

on:
  push:
    branches: [main, master, deploy]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "✅ Deployment - Project Ready"



